using System;
using System.Collections.Generic;

namespace qGen.Providers
{
        public class AnsiSettings : ProviderSettings
        {
                public AnsiSettings()
                {
                        this.Keywords = new Dictionary<string, string>() {
                                { "SERIAL", "INTEGER GENERATED BY DEFAULT AS IDENTITY" },
                                { "BLOB", "VARBINARY" },
                                { "TINYINT", "INTEGER" },
                                { "SMALLINT", "INTEGER" },
                                { "MEDIUMINT", "INTEGER" },
                                { "TIMESTAMP", "TIMESTAMP" },
                                { "DATETIME", "TIMESTAMP" },
                                { "CREATETABLE_OPTIONS", "" },
                                { "DEFERRABLE", "" }
                        };
                }
        }
}
